apiVersion: v1
kind: Secret
metadata:
  name: jfrogcred
  namespace: taxi
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJ0YXhpYm9vay5qZnJvZy5pbyI6IHsKCQkJImF1dGgiOiAiYzJGcGRHVnFPbE5BYVRFeU16UTFOamM0T1RFd01URXhNZz09IgoJCX0KCX0KfQ==
type: kubernetes.io/dockerconfigjson
